import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

import { readTextIfPresent, walkFiles } from "../util/fs.ts";
import type { CheckContext } from "../validation/context.ts";
import { error, type Issue } from "../validation/types.ts";
import { ADAPTATIONS_FILE, loadAdaptationFragments, renderAdaptations } from "../validation/provenance.ts";
import { HOST_IDS, type HostId } from "./hosts.ts";
import { planBundle, type BundlePlan, type PlanOptions } from "./plan.ts";

export interface BuildOptions extends PlanOptions {
  hosts?: ReadonlyArray<HostId>;
}

export function planAll(ctx: CheckContext, options: BuildOptions): BundlePlan[] {
  return (options.hosts ?? HOST_IDS).map((host) => planBundle(ctx, host, options));
}

function distDir(host: HostId): string {
  return `dist/${host}`;
}

/**
 * `planBundle` runs once per host, and most of what it reports is a fact about
 * the source tree rather than about a bundle: a skill with no SKILL.md, an
 * unparseable skill.yaml, a profile naming a skill the catalog does not declare.
 * Each comes back byte-identical from every plan, and a problem that cannot be
 * fixed per target and does not differ per target is one problem -- reporting it
 * once per host doubles the error count that everyone reads as a progress
 * number, and leaves two identical rows that read as a bug in the reporter.
 *
 * Collapsing on the whole diagnostic rather than on the rule is what makes this
 * safe: every genuinely per-target finding names its bundle or its adapter in
 * the file column -- `dist/<host>/...` for dist-missing, dist-stale and
 * dist-extra, `adapters/<host>/...` for an unknown restriction -- so no two of
 * them are ever identical and none is merged away.
 */
function collapseDuplicates(issues: ReadonlyArray<Issue>): Issue[] {
  const seen = new Set<string>();
  const out: Issue[] = [];
  for (const issue of issues) {
    const key = [issue.severity, issue.rule, issue.file, issue.line ?? "", issue.skipped ?? "", issue.message].join(
      "\u0000",
    );
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(issue);
  }
  return out;
}

export interface BuildResult {
  issues: Issue[];
  /**
   * The profile the bundles were planned with, so the command can report the
   * selection that happened rather than working it out a second time. The two
   * derivations had stopped agreeing: the plan recorded `"all"` for a build
   * that named no profile while the command announced the catalog's default.
   */
  profile: string;
}

export function writeBundles(ctx: CheckContext, options: BuildOptions): BuildResult {
  const plans = planAll(ctx, options);
  const issues = plans.flatMap((plan) => plan.issues);
  const profile = plans.at(-1)?.profile ?? "all";
  // A failure in any host must leave every installed bundle intact.
  if (issues.some((issue) => issue.severity === "error")) return { issues: collapseDuplicates(issues), profile };
  for (const plan of plans) {
    const outRoot = join(ctx.root, distDir(plan.host));
    rmSync(outRoot, { recursive: true, force: true });
    for (const file of plan.files.values()) {
      const target = join(outRoot, file.path);
      mkdirSync(dirname(target), { recursive: true });
      writeFileSync(target, file.contents);
    }
  }

  return { issues: collapseDuplicates(issues), profile };
}

/** Verify dist/ matches what a build would emit. Writes nothing. */
export function checkBundles(ctx: CheckContext, options: BuildOptions): Issue[] {
  const issues: Issue[] = [];

  for (const plan of planAll(ctx, options)) {
    issues.push(...plan.issues);
    const dir = distDir(plan.host);
    const onDisk = new Set(walkFiles(ctx.root, dir).map((p) => p.slice(dir.length + 1)));

    for (const file of plan.files.values()) {
      const actual = readTextIfPresent(join(ctx.root, dir, file.path));
      if (actual === null) {
        issues.push(
          error(
            "packaging.dist-missing",
            `${dir}/${file.path}`,
            "Generated by ak build but absent from dist/. Run ak build.",
          ),
        );
        continue;
      }
      onDisk.delete(file.path);
      if (actual !== file.contents) {
        issues.push(
          error(
            "packaging.dist-stale",
            `${dir}/${file.path}`,
            "Content differs from what ak build would emit. Run ak build.",
          ),
        );
      }
    }

    for (const extra of [...onDisk].sort()) {
      issues.push(
        error(
          "packaging.dist-extra",
          `${dir}/${extra}`,
          "Present in dist/ but not generated by ak build. Run ak build.",
        ),
      );
    }
  }

  return collapseDuplicates(issues);
}

/**
 * Render provenance/adaptations.yaml from its fragments.
 *
 * This is a source-tree artifact rather than a bundle file: NOTICE, README,
 * AGENTS.md and catalog.yaml all point at the path, so it is generated and
 * committed. It is written before the bundles and independently of them, so a
 * tree whose skills are not yet authored still gets a correct attribution file.
 * Conflicting fragments stop the write: half a merge is worse than none.
 */
export function writeAdaptations(ctx: CheckContext): Issue[] {
  const { rows, issues } = loadAdaptationFragments(ctx.root);
  if (issues.some((i) => i.severity === "error")) return issues.filter((i) => i.severity === "error");

  const target = join(ctx.root, ADAPTATIONS_FILE);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, renderAdaptations(rows));
  return [];
}
